import { AuditResult } from '@/types/audit'

export function getMockAuditResult(brand: string, category: string, url: string, competitors: string[]): AuditResult {
  return {
    brand,
    category,
    url,
    auditedAt: new Date().toISOString(),
    seo: {
      domainRating: 42,
      urlRating: 38,
      backlinks: 14820,
      referringDomains: 487,
      dofollowPct: '68%',
      organicKeywords: 3240,
      estimatedTraffic: 28500,
      topPages: [
        { path: '/', traffic: 12400, keywords: 820 },
        { path: '/products', traffic: 4200, keywords: 340 },
        { path: '/about', traffic: 2100, keywords: 180 },
        { path: '/blog/oat-milk-guide', traffic: 1800, keywords: 420 },
        { path: '/where-to-buy', traffic: 980, keywords: 160 },
      ],
      technical: [
        { label: 'Title tag', status: 'ok' },
        { label: 'Meta description', status: 'ok' },
        { label: 'Canonical tag', status: 'ok' },
        { label: 'H1 present', status: 'ok' },
        { label: 'Schema markup', status: 'fail' },
        { label: 'Open Graph tags', status: 'ok' },
        { label: 'robots.txt', status: 'ok' },
        { label: 'sitemap.xml', status: 'fail' },
      ],
    },
    ai: {
      summary: {
        ais: 68,
        mentionRate: 70,
        shareOfVoice: 42,
        avgPosition: 1.8,
        top3RatePct: 85,
        sentimentPositivePct: 62,
        sentimentNeutralPct: 28,
        sentimentNegativePct: 10,
        dominantFraming: 'premium sustainable oat milk brand',
        aggregateStrengths: ['Barista-grade texture', 'Southeast Asia availability', 'Sustainability credentials'],
        aggregateWeaknesses: ['Premium price point', 'Limited flavour range', 'Less known outside Singapore'],
      },
      firstMentionShare: '58%',
      engines: [
        {
          engine: 'chatgpt',
          ais: 72,
          mentionRate: 80,
          shareOfVoice: 45,
          top3RatePct: 90,
          queries: [
            { query: `best ${category} brands`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `${brand} review`, appears: true, position: 1, mentions: 5, sentiment: 'positive' },
            { query: `top ${category} options`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
            { query: `${brand} vs alternatives`, appears: true, position: 1, mentions: 4, sentiment: 'positive' },
            { query: `${category} recommendation`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `is ${brand} worth buying`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `${category} for everyday use`, appears: true, position: 3, mentions: 2, sentiment: 'neutral' },
            { query: `${brand} quality`, appears: true, position: 1, mentions: 4, sentiment: 'positive' },
            { query: `affordable ${category}`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `${category} market leaders`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
          ],
        },
        {
          engine: 'perplexity',
          ais: 65,
          mentionRate: 70,
          shareOfVoice: 38,
          top3RatePct: 80,
          queries: [
            { query: `best ${category} brands`, appears: true, position: 2, mentions: 2, sentiment: 'positive' },
            { query: `${brand} review`, appears: true, position: 1, mentions: 4, sentiment: 'positive' },
            { query: `top ${category} options`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `${brand} vs alternatives`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
            { query: `${category} recommendation`, appears: true, position: 3, mentions: 1, sentiment: 'neutral' },
            { query: `is ${brand} worth buying`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `${category} for everyday use`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `${brand} quality`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `affordable ${category}`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `${category} market leaders`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
          ],
        },
        {
          engine: 'gemini',
          ais: 58,
          mentionRate: 60,
          shareOfVoice: 35,
          top3RatePct: 75,
          queries: [
            { query: `best ${category} brands`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
            { query: `${brand} review`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `top ${category} options`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `${brand} vs alternatives`, appears: true, position: 2, mentions: 2, sentiment: 'neutral' },
            { query: `${category} recommendation`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `is ${brand} worth buying`, appears: true, position: 2, mentions: 2, sentiment: 'positive' },
            { query: `${category} for everyday use`, appears: true, position: 3, mentions: 1, sentiment: 'neutral' },
            { query: `${brand} quality`, appears: true, position: 1, mentions: 3, sentiment: 'positive' },
            { query: `affordable ${category}`, appears: false, position: null, mentions: 0, sentiment: null },
            { query: `${category} market leaders`, appears: false, position: null, mentions: 0, sentiment: null },
          ],
        },
      ],
    },
    benchmark: [
      {
        rank: 1,
        name: brand,
        domain: new URL(url).hostname,
        mentions: 42,
        visibility: 70,
        firstMentionShare: 58,
        sentiment: 'positive',
        isTarget: true,
        isCompetitor: false,
      },
      ...(competitors[0] ? [{
        rank: 2,
        name: competitors[0],
        domain: competitors[0].toLowerCase().replace(/\s+/g, '') + '.com',
        mentions: 38,
        visibility: 62,
        firstMentionShare: 44,
        sentiment: 'positive' as const,
        isTarget: false,
        isCompetitor: true,
      }] : []),
      ...(competitors[1] ? [{
        rank: 3,
        name: competitors[1],
        domain: competitors[1].toLowerCase().replace(/\s+/g, '') + '.com',
        mentions: 24,
        visibility: 45,
        firstMentionShare: 28,
        sentiment: 'neutral' as const,
        isTarget: false,
        isCompetitor: true,
      }] : []),
      {
        rank: 4,
        name: 'Alpro',
        domain: 'alpro.com',
        mentions: 18,
        visibility: 30,
        firstMentionShare: 15,
        sentiment: 'neutral' as const,
        isTarget: false,
        isCompetitor: false,
      },
    ],
    competitors: competitors.map((comp, i) => ({
      name: comp,
      domain: comp.toLowerCase().replace(/\s+/g, '') + '.com',
      domainRating: i === 0 ? 61 : 48,
      backlinks: i === 0 ? 284000 : 52000,
      organicKeywords: i === 0 ? 18400 : 8200,
      aiScore: i === 0 ? 79 : 52,
      firstMentionShare: i === 0 ? '44%' : '28%',
    })),
  }
}
